# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('py_proj_man', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DurationField(null=True)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='py_proj_man.Budget'),
        ),
    ]
