# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_proj_man', '0002_auto_20171003_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('baseline', models.DateTimeField(null=True)),
                ('budget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='py_proj_man.Budget')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='py_proj_man.Task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py_proj_man.Project')),
            ],
        ),
    ]
