# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_proj_man', '0004_auto_20171003_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_prerequisites_+', to='py_proj_man.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='py_proj_man.Budget'),
        ),
    ]
