# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_proj_man', '0007_auto_20171003_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='baseline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
