# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_proj_man', '0002_auto_20171003_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
                ('money', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='baseline',
            field=models.DateTimeField(null=True),
        ),
    ]
