# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:04
from __future__ import unicode_literals

from django.db import migrations
import py_proj_man.models


class Migration(migrations.Migration):

    dependencies = [
        ('py_proj_man', '0004_auto_20171003_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=py_proj_man.models.Budget(blank=True),
        ),
    ]
