# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_proj_man', '0005_auto_20171003_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
    ]
